<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <ItemGroup>
    <ProjectReference Include="..\src\AiBlogResearch.WebApi\AiBlogResearch.WebApi.csproj" />
    <ProjectReference Include="..\src\McpServer.WebApi\McpServer.WebApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.NodeJs" Version="9.5.2" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>ea27b7e3-b78a-4698-bc64-e364f1a8d025</UserSecretsId>
  </PropertyGroup>

</Project>
